[package]
name = "win-clipboard"
version = "2.0.0"
authors = ["Sindre Sorhus <sindresorhus@gmail.com>", "Vsevolod Strukchinsky <floatdrop@gmail.com>"]

[dependencies]
clipboard-win = "4"
image = "0.23.12"
